# Version format
version: 1.0.{build}

# Build worker image
image: Visual Studio 2019

# Build platform
platform: Any CPU

# Build Configuration
configuration: Debug

# MSBuild settings
build:
  project: GetAllIssuesPj.csproj
  verbosity: quiet
  
# Execute script before build
before_build:
 - nuget restore GetAllIssuesPj.csproj

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  # pushing a single file
  - path: artifact.txt

deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: artifact.txt           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
 
 
